### ISSUE TITLE
DP: Meta: Evaluate moving to codewalks

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#376]
Our tutorials are and look good Do we want to move to a code-walk format or are we happy with their functionality now?

**Supporting**
Codewalk ex: https://golang.org/doc/codewalk/functions/

Possible Path: It may be valuable to utilize/update our DP "consumable repo" standards to support auto-generation of code-walks via a tool that compiles properly annotated src files and README files into a code-walk. This would also allow injection of the annotated code into a more traditional style tutorial (as the DP is currently)

**AC**
- [ ] evaluate and put decision in `# Results`
- [ ] describe where codewalks will live within website (we want to keep inline tutorials)
- [ ] if answer is no, close codewalk meta stories. in Steemworks backlog.
- [ ] if answer is yes, add to prioritized roadmap
