### ISSUE TITLE
DP: META - Create recommended standard/structure for repo doc files (2)

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#379]
Continue the process outlined in #297 - formalize the structure discussed there, and extend it with specific tutorial structure recommendations that include notation within `.md` files and `.js`, `.py`,`.rb` files so that links between text and code blocks can be established, and parsed by devportal scripts into "inline" tutorials as we have now, and code-walks.

**AC**
The following in `# Results`
- [ ] specification for overall repo `meta.json`
- [ ] specification for individual tutorial `meta.json`
- [ ] specification for tutorial file-structure, and file-format so that src files & `.md` files can have appropriate bits linked

**Comment by inertia186** [comment]
Yep, that's a good start.  In terms of what we *really* need right now, it's mostly just `toc-title` and `toc-description`.  The rest of it is future-proofing.
